In [4]:
from typing import List

In [20]:
sents = [
    ["I", "am", "ahmed"],
    ["Hi"],
    ["adf","Xsd","Yss","zzzs"]
]
sents

[['I', 'am', 'ahmed'], ['Hi'], ['adf', 'Xsd', 'Yss', 'zzzs']]

In [21]:
def pad_sents(sents: List[str], pad_token:str):
    """ Pad list of sentences according to the longest sentence in the batch.
        The paddings should be at the end of each sentence.
    @param sents (list[list[str]]): list of sentences, where each sentence
                                    is represented as a list of words
    @param pad_token (str): padding token
    @returns sents_padded (list[list[str]]): list of sentences where sentences shorter
        than the max length sentence are padded out with the pad_token, such that
        each sentences in the batch now has equal length.
    """
    sents_padded = []

    ### YOUR CODE HERE (~6 Lines)
    max_len = max([len(sent) for sent in sents])
    for sentence in sents:
        new_sentence = sentence.copy()
        len_diff = max_len - len(sentence)
        new_sentence.extend([pad_token]*len_diff)
        sents_padded.append(new_sentence)
    ### END YOUR CODE

    return sents_padded

In [22]:
pad_sents(sents,"<pad>")

[['I', 'am', 'ahmed', '<pad>'],
 ['Hi', '<pad>', '<pad>', '<pad>'],
 ['adf', 'Xsd', 'Yss', 'zzzs']]

In [23]:
import torch

In [53]:
x = torch.randn(2, 3, 5)

In [54]:
x.size()

torch.Size([2, 3, 5])

In [55]:
x = torch.permute(x, (1, 2, 0))
x.size()

torch.Size([3, 5, 2])

In [56]:
x = torch.permute(x, (2, 0, 1))
x.size()

torch.Size([2, 3, 5])

In [58]:
y = torch.randn(2, 3, 5)

In [59]:
y[0].size()

torch.Size([3, 5])

In [64]:
y

tensor([[[-0.3509, -1.0029, -1.8906, -0.7892, -0.9271],
         [ 0.9371, -0.0167,  0.5179,  0.2678,  0.0057],
         [ 0.5242, -1.1796, -0.3857,  0.6410,  0.8645]],

        [[ 0.7194, -0.3847,  0.2632,  0.5064,  0.7198],
         [-0.7187,  1.0472,  1.6177, -2.3969,  1.2368],
         [ 0.8809,  1.8335, -1.0884,  1.1548,  0.5726]]])

In [63]:
torch.cat((y[0],y[1]),1)

tensor([[-0.3509, -1.0029, -1.8906, -0.7892, -0.9271,  0.7194, -0.3847,  0.2632,
          0.5064,  0.7198],
        [ 0.9371, -0.0167,  0.5179,  0.2678,  0.0057, -0.7187,  1.0472,  1.6177,
         -2.3969,  1.2368],
        [ 0.5242, -1.1796, -0.3857,  0.6410,  0.8645,  0.8809,  1.8335, -1.0884,
          1.1548,  0.5726]])

In [65]:
z = torch.randn(5, 3, 4) # (tgt_len, b, e)

In [72]:
z

tensor([[[-1.3341, -0.3138, -0.5057,  0.6869],
         [-0.8903,  0.5057, -0.5412,  1.5795],
         [-0.0915, -0.6573,  0.7392,  0.3845]],

        [[ 1.0887, -0.4675, -0.5094,  0.4930],
         [ 1.4384, -0.2551, -0.4001,  0.0847],
         [ 1.8650,  0.9689, -1.9432,  0.4301]],

        [[ 0.9754, -0.8197, -0.8971, -2.9545],
         [-0.5925, -0.0174,  0.7758, -0.7600],
         [ 0.5406, -0.9301,  0.2892, -0.6570]],

        [[ 0.2858,  0.8019, -0.0269,  2.2111],
         [ 0.2777,  0.5108, -0.3202,  0.3370],
         [ 1.9752,  0.3999,  0.0913, -1.7724]],

        [[-0.2004, -1.0904, -0.3963,  0.4045],
         [-1.6428, -0.6829, -1.0945,  1.4011],
         [ 1.3094, -0.6929,  0.5677,  1.1279]]])

In [80]:
torch.split(z,1)[0].squeeze(0)

tensor([[-1.3341, -0.3138, -0.5057,  0.6869],
        [-0.8903,  0.5057, -0.5412,  1.5795],
        [-0.0915, -0.6573,  0.7392,  0.3845]])

In [81]:
a = torch.randn((5,3))
b = torch.randn((5,10))

In [82]:
c = torch.concat((a,b),dim=1)

In [84]:
c.size()

torch.Size([5, 13])

In [85]:
a

tensor([[ 1.2844,  2.1857, -0.3052],
        [-1.2620,  2.4478,  0.6717],
        [-2.2357, -0.6081, -1.8140],
        [ 2.9591, -1.0048, -0.4789],
        [ 1.5579, -0.1271,  0.2441]])

In [86]:
b

tensor([[ 1.4943,  2.6412, -0.0402,  0.3177,  0.2232, -1.2134, -0.6537,  0.6222,
          0.3801, -1.7011],
        [ 0.6830,  0.3107, -0.2739,  0.1173, -0.6853,  1.1872,  0.4568,  1.9872,
          1.2700,  0.3948],
        [-1.1232, -0.1174,  0.4050, -2.0123,  3.4327,  0.3601,  0.9009,  0.3474,
         -0.2817, -0.1726],
        [ 0.4146,  0.4845,  0.5939, -0.1040,  0.2251,  0.6211, -1.2236,  0.0369,
          0.1952, -0.1406],
        [ 1.0844, -0.4709, -0.4734, -0.1260,  0.3122,  0.5078, -1.3600, -0.0278,
          0.3842,  1.4284]])

In [88]:
c

tensor([[ 1.2844,  2.1857, -0.3052,  1.4943,  2.6412, -0.0402,  0.3177,  0.2232,
         -1.2134, -0.6537,  0.6222,  0.3801, -1.7011],
        [-1.2620,  2.4478,  0.6717,  0.6830,  0.3107, -0.2739,  0.1173, -0.6853,
          1.1872,  0.4568,  1.9872,  1.2700,  0.3948],
        [-2.2357, -0.6081, -1.8140, -1.1232, -0.1174,  0.4050, -2.0123,  3.4327,
          0.3601,  0.9009,  0.3474, -0.2817, -0.1726],
        [ 2.9591, -1.0048, -0.4789,  0.4146,  0.4845,  0.5939, -0.1040,  0.2251,
          0.6211, -1.2236,  0.0369,  0.1952, -0.1406],
        [ 1.5579, -0.1271,  0.2441,  1.0844, -0.4709, -0.4734, -0.1260,  0.3122,
          0.5078, -1.3600, -0.0278,  0.3842,  1.4284]])